# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from gameServicer import gameServer_pb2 as gameServicer_dot_gameServer__pb2


class gameServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Move = channel.unary_unary(
        '/gameServer.gameService/Move',
        request_serializer=gameServicer_dot_gameServer__pb2.Direction.SerializeToString,
        response_deserializer=gameServicer_dot_gameServer__pb2.Position.FromString,
        )
    self.MagicAttack = channel.unary_unary(
        '/gameServer.gameService/MagicAttack',
        request_serializer=gameServicer_dot_gameServer__pb2.Magic.SerializeToString,
        response_deserializer=gameServicer_dot_gameServer__pb2.Magic.FromString,
        )
    self.PhysicalAttack = channel.unary_unary(
        '/gameServer.gameService/PhysicalAttack',
        request_serializer=gameServicer_dot_gameServer__pb2.Stamina.SerializeToString,
        response_deserializer=gameServicer_dot_gameServer__pb2.Stamina.FromString,
        )
    self.Heal = channel.unary_unary(
        '/gameServer.gameService/Heal',
        request_serializer=gameServicer_dot_gameServer__pb2.Magic.SerializeToString,
        response_deserializer=gameServicer_dot_gameServer__pb2.Health.FromString,
        )


class gameServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Move(self, request, context):
    """Move will be used to move a character around a 2d map
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def MagicAttack(self, request, context):
    """attack will be a physical or magic attack and requires stamina or magic
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PhysicalAttack(self, request, context):
    """physical attack will be an attack with a weapon
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Heal(self, request, context):
    """Heal will heal a character and has to be done with magic
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_gameServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Move': grpc.unary_unary_rpc_method_handler(
          servicer.Move,
          request_deserializer=gameServicer_dot_gameServer__pb2.Direction.FromString,
          response_serializer=gameServicer_dot_gameServer__pb2.Position.SerializeToString,
      ),
      'MagicAttack': grpc.unary_unary_rpc_method_handler(
          servicer.MagicAttack,
          request_deserializer=gameServicer_dot_gameServer__pb2.Magic.FromString,
          response_serializer=gameServicer_dot_gameServer__pb2.Magic.SerializeToString,
      ),
      'PhysicalAttack': grpc.unary_unary_rpc_method_handler(
          servicer.PhysicalAttack,
          request_deserializer=gameServicer_dot_gameServer__pb2.Stamina.FromString,
          response_serializer=gameServicer_dot_gameServer__pb2.Stamina.SerializeToString,
      ),
      'Heal': grpc.unary_unary_rpc_method_handler(
          servicer.Heal,
          request_deserializer=gameServicer_dot_gameServer__pb2.Magic.FromString,
          response_serializer=gameServicer_dot_gameServer__pb2.Health.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'gameServer.gameService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
