# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from gameServer import gameServer_pb2 as gameServer_dot_gameServer__pb2


class gameServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Move = channel.unary_unary(
        '/gameServer.gameService/Move',
        request_serializer=gameServer_dot_gameServer__pb2.Direction.SerializeToString,
        response_deserializer=gameServer_dot_gameServer__pb2.Position.FromString,
        )
    self.Attack = channel.unary_unary(
        '/gameServer.gameService/Attack',
        request_serializer=gameServer_dot_gameServer__pb2.Magic.SerializeToString,
        response_deserializer=gameServer_dot_gameServer__pb2.Stamina.FromString,
        )
    self.Heal = channel.unary_unary(
        '/gameServer.gameService/Heal',
        request_serializer=gameServer_dot_gameServer__pb2.Magic.SerializeToString,
        response_deserializer=gameServer_dot_gameServer__pb2.Health.FromString,
        )


class gameServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Move(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Attack(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Heal(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_gameServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Move': grpc.unary_unary_rpc_method_handler(
          servicer.Move,
          request_deserializer=gameServer_dot_gameServer__pb2.Direction.FromString,
          response_serializer=gameServer_dot_gameServer__pb2.Position.SerializeToString,
      ),
      'Attack': grpc.unary_unary_rpc_method_handler(
          servicer.Attack,
          request_deserializer=gameServer_dot_gameServer__pb2.Magic.FromString,
          response_serializer=gameServer_dot_gameServer__pb2.Stamina.SerializeToString,
      ),
      'Heal': grpc.unary_unary_rpc_method_handler(
          servicer.Heal,
          request_deserializer=gameServer_dot_gameServer__pb2.Magic.FromString,
          response_serializer=gameServer_dot_gameServer__pb2.Health.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'gameServer.gameService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
